version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: language-course-api
    ports:
      - "7006:7006"
    depends_on:
      - mongolanguagecourse
  mongolanguagecourse:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongolanguagecourse
